### ISSUE TITLE
Error in coef(test.reg)[2, 1] : subscript out of bounds

### ISSUE THREAD

**Issue by abandus** [robjhyndman/tsfeatures#14]
Hello, 

I am getting the following error:

  f<-tsfeatures(listofts,features=c("frequency","pacf_features","stl_features","arch_stat","crossing_points","flat_spots","holt_parameters","lumpiness","stability","max_level_shift","max_var_shift","max_kl_shift","nonlinearity","unitroot_kpss","unitroot_pp"))
  

Error in coef(test.reg)[2, 1] : subscript out of bounds

Any idea?

**Comment by robjhyndman** [comment]
I can't reproduce this. Please provide a minimal reproducible example.

**Comment by jmablans** [comment]
This is probably related to #28 

below a reprex:

```
ts <- as.ts(c(0,1))
tsfeatures(ts, features = c('unitroot_pp'))
# Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...) : 0 (non-NA) cases

ts <- as.ts(c(1,1,0))
tsfeatures(ts, features = c('unitroot_pp'))
# error : Error in coef(test.reg)[2, 1] : subscript out of bounds

ts <- as.ts(c(1,1,1,0))
tsfeatures(ts, features = c('unitroot_pp'))
# error : Error in coef(test.reg)[2, 1] : subscript out of bounds

ts <- as.ts(c(1,0,1))
tsfeatures(ts, features = c('unitroot_pp'))
# no error, result:
# # A tibble: 1 x 1
#   unitroot_pp
#         <dbl>
# 1          -4

ts <- as.ts(c(0, 1, 1))
tsfeatures(ts, features = c('unitroot_pp'))
# no error, result:
# A tibble: 1 x 1
#   unitroot_pp
#         <dbl>
# 1         NaN

ts <- as.ts(c(1,1,0,0))
tsfeatures::tsfeatures(ts, features = c('unitroot_pp'))
# no error, result :
# # A tibble: 1 x 1
#   unitroot_pp
#          <dbl>
# 1      -0.938
```

**Comment by robjhyndman** [comment]
These errors are now captured and returned as NAs in https://github.com/robjhyndman/tsfeatures/commit/108cb72677e11a76b04b83398858f411a18b0edb. The computation is done in the urca package, so the real problem is there.
