### ISSUE TITLE
Error on webpage

### ISSUE THREAD

**Issue by sbcalaff** [robjhyndman/tsfeatures#26]
The webpage of this URL ([https://pkg.robjhyndman.com/tsfeatures/articles/tsfeatures.html#crossing_points](https://pkg.robjhyndman.com/tsfeatures/articles/tsfeatures.html#crossing_points)) states:

> crossing points are defined as the number of times a time series crosses the **_mean_** line.

I think it should be the **median line**, as in the reference manual:

> crossing points are defined as the number of times a time series crosses the **_median_** line.

The same for this URL: 
[https://cran.r-project.org/web/packages/tsfeatures/vignettes/tsfeatures.html](https://cran.r-project.org/web/packages/tsfeatures/vignettes/tsfeatures.html)

**Comment by robjhyndman** [comment]
Thanks. Now fixed via https://github.com/robjhyndman/tsfeatures/commit/e44e781bfcee106cc52833689773692a170e0297
