### ISSUE TITLE
Error in unitroot_pp

### ISSUE THREAD

**Issue by catapulta** [robjhyndman/tsfeatures#28]
Hello, I'm getting an error when running the following:

```
tsfeatures::unitroot_pp(c(rep(0, 10), 2))

Error in coef(test.reg)[2, 1]: subscript out of bounds
Traceback:

1. unitroot_pp(er$x + 10)
2. urca::ur.pp(x)
```

Env:
R 3.6.1
tsfeatures_1.0.1

**Comment by robjhyndman** [comment]
This error is actually in the `urca` package as the traceback shows. You should report it at https://github.com/bpfaff/urca/issues

**Comment by catapulta** [comment]
Thanks. Reported here: https://github.com/bpfaff/urca/issues/2
