### ISSUE TITLE
unitroot_kpss and unitroot_pp functionality different from description

### ISSUE THREAD

**Issue by MichaelBehr** [robjhyndman/tsfeatures#29]
Description of unitroot_kpss and unitroot_pp is as follows:

**_unitroot_kpss_** computes the statistic for the Kwiatkowski et al. unit root test with **linear trend** and **lag 1**. **_unitroot_pp_** computes the statistic for the ''Z-alpha” version of Phillips & Perron unit root test with **constant trend** and **lag 1**.

**unitroot_kpss** calls the Kwiatkowski Et Al. Unit Root Test from the **urca** package as:

_urca::ur.kpss(x) @teststat_ which is equivalent to:
 _urca::ur.kpss(x, type = c("mu"),lags = c('short'))@teststat_

This function input is different than the description, comparing against a constant trend (instead of linear) and using √4×(n/100) as the lags instead of 1. The proper call in the **_unitroot_kpss_** function should be:

_urca::ur.kpss(x, type = c("tau"),use.lag=1)_

Similarily, **_unitroot_pp_** uses the wrong lag as well. It calls:

_urca::ur.pp(x)@teststat_ which is equivalent to:
_urca::ur.pp(x,type='Z-alpha',lags='short',model='constant')@teststat_

According to the description it should be calling instead: 

_urca::ur.pp(x,use.lag=1)@teststat_

**Comment by robjhyndman** [comment]
Thanks. The documentation has been updated to match the function in https://github.com/robjhyndman/tsfeatures/commit/7948e9c8708190c474505dcd13534ef49fbadb2f
