### ISSUE TITLE
constant crashes on R 4.0.0

### ISSUE THREAD

**Issue by krz** [robjhyndman/tsfeatures#36]
I get constant crashes using this package with new R 4.0.0. It worked fine previously

**Comment by robjhyndman** [comment]
Please provide a minimal example that causes the problem.

**Comment by krz** [comment]
after some further testing I found that it's a problem of my OpenBLAS configuration and R 4.0.0 and not related to `tsfeatures` specifically. I will still revert back to 3.6.3 to be safe.
Can be closed, sorry for the inconvenience.
