### ISSUE TITLE
Question for the new entropy() function

### ISSUE THREAD

**Issue by chenx2018** [robjhyndman/tsfeatures#37]
New entropy() function has removed dependency on ForeCA, but it gets **very different** value from ForeCA approach. 

I have used the order version package to calculate ts features in order to apply my meta model of FFORMA. Now since the entropy() value changed a lot, should I re-train the meta model for FFORMA?

**Comment by robjhyndman** [comment]
Spectral entropy requires estimation of the spectral density and there are many ways to do that. When I re-implemented the method I chose to use a different method from ForeCA, so the estimates of entropy have also changed. Yes, you probably need to retrain any model that uses these values.

**Comment by chenx2018** [comment]
Thanks a lot!
