### ISSUE TITLE
Typo in docs (Introduction to the tsfeatures package)

### ISSUE THREAD

**Issue by Deleetdk** [robjhyndman/tsfeatures#40]
Minor typo here:

https://pkg.robjhyndman.com/tsfeatures/articles/tsfeatures.html

![Screenshot from 2020-11-01 20-57-09](https://user-images.githubusercontent.com/6759913/97812898-e64d0480-1c84-11eb-9279-a3f41ce32fac.png)

**Comment by robjhyndman** [comment]
Thanks. Now fixed (it will take a few minutes to regenerate)
