### ISSUE TITLE
 WISH: URL and BugReports

### ISSUE THREAD

**Issue by HenrikBengtsson** [robjhyndman/tsfeatures#43]
Please consider adding `URL` and `BugReports` fields to this package `DESCRIPTION` file so that it is easy to find this repo from <https://cran.r-project.org/package=tsfeatures>.

**Comment by robjhyndman** [comment]
These have been part of the DESCRIPTION file since the very first commit: https://github.com/robjhyndman/tsfeatures/commit/10f8b1a22190379a051809233f2ee55099d61bc9

**Comment by HenrikBengtsson** [comment]
Sorry, my bad. Yeah, they're definitely there; https://cran.r-project.org/web/packages/tsfeatures/index.html.  I was [juggling many packages](https://github.com/HenrikBengtsson/future/issues/546) at the same time and must have mixed yours up with another. Sorry about the noise.
