### ISSUE TITLE
NOTICE: plan(multiprocess) of future is deprecated

### ISSUE THREAD

**Issue by HenrikBengtsson** [robjhyndman/tsfeatures#44]
Hi.

This is a friendly reminder that [`plan(multiprocess)`](https://future.futureverse.org/reference/multiprocess.html) of the [**future**](https://cran.r-project.org/package=future) package is _deprecated_ since **future** 1.20.0 (2020-11-03).  It will eventually become _defunct_ and removed.  The background for this can be found in <https://github.com/HenrikBengtsson/future/issues/420>.

Your **tsfeatures** package relies on `multiprocess`, cf. <https://github.com/robjhyndman/tsfeatures/search?q=multiprocess>.

Please migrate your code to the platform-independent `plan(multisession)` or the Linux/macOS-specific `plan(multicore)`.  If you want to emulate what `multiprocess` does, you can do something like:

```r
  if (parallelly::supportsMulticore()) {
    oplan <- plan(multicore)
  } else {
    oplan <- plan(multisession)
  }
  on.exit(plan(oplan))
```

Thank you,

Henrik
(maintainer of the **future** package)

**Comment by robjhyndman** [comment]
Thanks Henrik. Fixed in https://github.com/robjhyndman/tsfeatures/commit/b050091f17fa90281236dcc995f0465eebfddfe1

**Comment by HenrikBengtsson** [comment]
Just a friendly reminder that `multiprocess` will become defunct and eventually be removed.  When that happens, your package will break and risk being archived on CRAN.  My suggestion is to update to use `multisession` instead.

**Comment by robjhyndman** [comment]
We have updated to `multisession` as already noted above.

**Comment by HenrikBengtsson** [comment]
I was referring to the version on CRAN, which is from 2020-06-07

**Comment by robjhyndman** [comment]
Oh, sorry. I'll submit it to CRAN shortly.
