### ISSUE TITLE
package ‘tsfeatures’ is not available (for R version 3.5.2)

### ISSUE THREAD

**Issue by quantitative-technologies** [robjhyndman/tsfeatures#45]
> install.packages('tsfeatures', dependencies = TRUE)
Installing package into ‘/home/user/R/x86_64-pc-linux-gnu-library/3.5’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘tsfeatures’ is not available (for R version 3.5.2)

**Comment by mitchelloharawild** [comment]
The minimum R version for the package (as mentioned in the DESCRIPTION file) is 3.6.0.

**Comment by quantitative-technologies** [comment]
OK, thanks. I guess I should close this then.

Unfortunately, debian stable still uses R 3.5.
