### ISSUE TITLE
rolling window-based feature question

### ISSUE THREAD

**Issue by cdbale** [robjhyndman/tsfeatures#48]
@robjhyndman I have a question/concern about the implementation of the rolling-window based features (max_level_shift and max_var_shift - it may be occurring for max_kl_shift but I haven't dug into that one).

The description of these features says they measure the largest mean shift/var shift between two consecutive windows. I interpreted that to mean the largest mean/var shift between pairs of windows $\{[t, t+width], [t+1, t+width+1]\}$ for $t = 1,...,T-width-1$.

However, the current implementation of these features (see ```max_level_shift``` below) returns the largest absolute difference between windows of width $width$ that are also separated by $width$ time periods, *i.e.*, ```means <- abs(diff(rollmean, width)) ```. The only time the function behaves as I had expected is if I set the time series frequency to 1.

For my use case, I want to calculate these rolling window features for weekly time series over 104 time periods. The current implementation returns ```NA``` since there is not enough data to have windows separated by 54 time periods.

I believe changing ``` means <- abs(diff(rollmean, width)) ``` to ``` means <- abs(diff(rollmean, 1)) ``` would make the functions return what I expected. Please let me know if my interpretation is incorrect and if this is the desired behavior of the function.

``` R
max_level_shift <- function(x, width = ifelse(frequency(x) > 1,
                              frequency(x), 10
                            )) {
  suppressWarnings(rollmean <- try(RcppRoll::roll_mean(x, width, na.rm = TRUE), silent = TRUE))
  if ("try-error" %in% class(rollmean)) {
    maxmeans <- NA_real_
    maxidx <- NA_real_
  } else {
    means <- abs(diff(rollmean, width))
    if (length(means) == 0L) {
      maxmeans <- 0
      maxidx <- NA_real_
    }
    else if (all(is.na(means))) {
      maxmeans <- NA_real_
      maxidx <- NA_real_
    }
    else {
      maxmeans <- max(means, na.rm = TRUE)
      maxidx <- which.max(means) + 1L
    }
  }
  return(c(max_level_shift = maxmeans, time_level_shift = maxidx))
}
```

**Comment by robjhyndman** [comment]
The way it is implemented is as intended. We are trying to identify level shifts by finding the biggest difference in the level of the series between windows $[t, t+w]$ and $[t+w+1,t+2w]$ for any $t$.

If you allow the two windows to overlap, then most of the observations are identical, and you will be finding outlying observations rather than level shifts in the series.

Of course, there's nothing stopping you adapting the function to produce whatever feature you are interested in.

**Comment by cdbale** [comment]
Thanks! That makes a lot of sense.
