### ISSUE TITLE
Unused argument error

### ISSUE THREAD

**Issue by Jitu1701** [robjhyndman/tsfeatures#7]
Some of the functions do not allow for unused arguments due to which the following code fails

tsfeatures(tsdata, features = c("lumpiness","entropy"), width = 4) 
gives the error _Error in match.fun(features[i])(x, ...) : unused argument (width = 4)_

This is due to entropy <- function(x) adding ... as follows   
entropy <- function(x, ...) would help over come this issue.

**Comment by thiyangt** [comment]
fixed issue #7

**Comment by robjhyndman** [comment]
See https://github.com/robjhyndman/tsfeatures/commit/bf81822e0100b74f4381f08e1d5728afd9a5e28e
